### ISSUE TITLE
[BUG] Can't create SchedulerTask in Version v11.5.0-pre-alpha-1 

### ISSUE THREAD

**Issue by IngoMueller** [TYPO3-Solr/ext-solr#3116] opened 2021-12-08 12:19 UTC
**Describe the bug**
After installing TYPO3 v11.5.4-dev wich is the depenency from ext-solr v11.5.0-pre-alpha-1 i got an TypeError if i try to create a SchedulerTask over the Backendmodul.

**To Reproduce**
1. Install TYPO3 v11.5.4-dev
2. Install ext-solr v11.5.0-pre-alpha-1 
3. Go to Backendmodul Scheduler
4. Click on the Button "+" (Add Task)
5. see Error

**Expected behavior**
I can create a SchedulerTask for solr over the Backendmodul Scheduler.

**Screenshots**
<img width="1212" alt="Bildschirmfoto 2021-12-08 um 13 13 41" src="https://user-images.githubusercontent.com/9001720/145206637-361e7d70-4a44-4376-b781-e3b76ede2160.png">

**Used versions (please complete the following information):**
 - TYPO3 Version: v11.5.4-dev
 - EXT:solr Version: v11.5.0-pre-alpha-1 
 - Used Apache Solr Version: 11.1.2
 - PHP Version: 7.4.25
 - MySQL Version: 8.0.27

**Comment by dkd-kaehm** [comment] 2021-12-08 17:47
@IngoMueller 
Thanks for reporting and nice catch. 
The issue is fixed in [task/2976_TYPO3.11_compatibility](https://github.com/TYPO3-Solr/ext-solr/tree/task/2976_TYPO3.11_compatibility) branch and will be merged in release-11.5.x soonish.

**Closed by dkd-kaehm** 2021-12-08 17:47 UTC

**Comment by IngoMueller** [comment] 2021-12-09 10:22
@dkd-kaehm thanks for the Fix.
