### ISSUE TITLE
[BUG] JVM crash when using NumericRange facets

### ISSUE THREAD

**Issue by FlyKasual** [TYPO3-Solr/ext-solr#3907] opened 2023-12-05 08:24 UTC
**Describe the bug**
The JVM crashes with an "Out of Heap Memory" exception when using NumericRange facets

**To Reproduce**
1. Create a NumericRange facet
2. Index all records which have the corresponding field
3. Put a search results plugin on a page, which is initialized with the query "\*:\*"
4. Go to the above mentioned page

**Expected behavior**
One should see the search results as well as the facet(s). Instead one sees the message "The search is currently not available". The solr server becomes unresponsive at this point as the JVM crashes.

**Screenshots**
![Bildschirmfoto 2023-12-04 um 13 48 30](https://github.com/TYPO3-Solr/ext-solr/assets/29982045/48282a5a-f05e-49f9-8d67-19a1426f5bc4)

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.8
 - EXT:solr Version: 12.0.1
 - Used Apache Solr Version: 9.3.0, 9.4.0
 - PHP Version: 8.2.13

**Comment by dkd-kaehm** [comment] 2023-12-05 09:53
@FlyKasual 
Thanks for reporting. 
How many memory heap allocated for that server? 
Is it an ARM-arch host?

**Comment by FlyKasual** [comment] 2023-12-05 11:18
@dkd-kaehm After more fiddling around, I found that the issue only occurs, if one moves the range slider. If one manually sets the parameters via the url, things work fine. My suspicion is that the js library spams the solr with requests.

**Comment by dkd-kaehm** [comment] 2023-12-05 11:57
@FlyKasual 
Please increase the heap a little bit. E.g. to 756MB and check it again.

**Comment by FlyKasual** [comment] 2023-12-05 13:50
@dkd-kaehm Increased it to 4g. That seems to remedy this issue. However, now I see a 503 error, because the solr says "400 Bad Request".

**Comment by dkd-kaehm** [comment] 2023-12-05 14:57
OK, thanks. 
I'll close this issue.

The "400 Bad Request" is another issue. Please add comments to existing appropriate issue or open a new one, if you find the cause.

**Closed by dkd-kaehm** 2023-12-05 14:57 UTC
