### ISSUE TITLE
[BUG] tx_solr crashes with a DI exception (related to ApacheSolrForTypo3\Solr\Routing\RoutingService)

### ISSUE THREAD

**Issue by tehplague** [TYPO3-Solr/ext-solr#3015] opened 2021-09-06 08:52 UTC
**Describe the bug**
tx_solr crashes with a DI exception:

```
 [ Symfony\Component\DependencyInjection\Exception\RuntimeException ]                                                                                                                
  Cannot autowire service "ApacheSolrForTypo3\Solr\Domain\Search\Uri\SearchUriBuilder": argument "$routingService" of method "injectRoutingService()" references class "ApacheSolrFo  
  rTypo3\Solr\Routing\RoutingService" but no such service exists.                                                                                                                     
```

**To Reproduce**
I am running 10.4 with the following solr-related extensions:
```
apache-solr-for-typo3/solr                 11.1.1                       Apache Solr for TYPO3                                   
apache-solr-for-typo3/solrconsole          4.0.1                        Solrconsole: Less monkey business, more time for the important stuff                                         
apache-solr-for-typo3/solrfal              8.0.0                        Apache Solr for TYPO3 - File Indexing                                                                        
apache-solr-for-typo3/solrfluidgrouping    2.1.0                        Apache Solr for TYPO3                                                 
```

Even a simple `bin/typo3cms database:updateschema` fails with the exception above.

**Expected behavior**
tx_solr should not break the DI container

**Screenshots**
see above 

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.20
 - EXT:solr Version: 11.1.1.
 - PHP Version: 7.4.23

**Comment by dkd-kaehm** [comment] 2021-09-07 07:06
@tehplague 
Please refer to EXT:solr* Version matrix.
https://raw.githubusercontent.com/TYPO3-Solr/ext-solr/master/Documentation/Appendix/VersionMatrix.rst
So you want EXT:solrfal v.10.0.x EXT:solrfluidgrouping dev-master(v10.0.0 will be released this week).

**Comment by dkd-kaehm** [comment] 2021-09-07 07:22
@tehplague 
I can't reproduce the issue. 
Is TYPO3 in composer mode?

**Comment by tehplague** [comment] 2021-09-07 07:49
Yes, it is - hence the output from `composer show` above. :wink:

How can dependency resolution in `ApacheSolrForTypo3\Solr\Domain\Search\Uri\SearchUriBuilder` be related to the wrong version of solrfal being used? The exception refers to a class in solr, not solrfal.

**Comment by dkd-kaehm** [comment] 2021-09-07 09:25
> to the wrong version of solrfal being used? The exception refers to a class in solr, not solrfal.

Anyway the suggestion about Version matrix is still correct.

---

The `ApacheSolrForTypo3\Solr\Domain\Search\Uri\SearchUriBuilder` and `ApacheSolrForTypo3\Solr\Routing\RoutingService` are used in EXT:solr only. 
So please make sure the dumpautoload is executed after EXT:solr 11.1.1 installation.
As mentioned above, I can't reproduce the issue, neither on fresh EXT:solr install, nor on upgrade from 11.0.5 to 11.1.1.

I'll close this issue.
If you have some more infos about that issue, we can reopen it if it is needed.

**Closed by dkd-kaehm** 2021-09-07 09:25 UTC
