### ISSUE TITLE
[BUG] URI passed must be a string, but is of type "NULL" 

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Solr/ext-solr#3006] opened 2021-08-24 11:17 UTC
**Describe the bug**
After upgrading from solr 11.0.5 to solr 11.1.1. I can't search for all pages, files anymore with `*`

**To Reproduce**
When I search for `*` I get the error 
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1436717320: URI passed must be a string, but is of type "NULL" | InvalidArgumentException thrown in file /var/www/vhosts/xxx.my-provider.de/httpdocs/typo3cms/typo3_src-10.4.15/typo3/sysext/core/Classes/Http/Uri.php in line 108. Requested URL: https://www.my-domain.de/suche?tx_solr%%5Bq%%5D=* `

**Expected behavior**
I expect to see all pages, files and so on

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 10.4.20]
 - Browser: [firefox]
 - EXT:solr Version: [e.g. 11.1.1]
 - Used Apache Solr Version: [e.g. 8.8.0]
 - PHP Version: [7.4.22]
 - MySQL Version: [5.6]

**Comment by dkd-kaehm** [comment] 2021-08-24 11:52
@Hobokens 
I can't reproduce this issue. There are more infos needed.
Why the URL has to many percent signs? 
Which leads to `tx_solr%[q%]=*` ?

**Comment by Hobokens** [comment] 2021-08-24 18:08
@dkd-kaehm 
After some research, I identified this configuration file as the cause of the error
```
plugin.tx_solr.index.queue {
	tt_address = 1
	tt_address {
		table = tt_address
		lable = Personen

		additionalWhereClause = first_name NOT LIKE ''

		fields {
			abstract = position
			title = name

			content = SOLR_CONTENT
			content {
				field = title
			}

			url = TEXT
			url {
				typolink.parameter.field = detail
				typolink.returnLast = url
				typolink.useCacheHash = 0
			}
		}
		excludeContentByClass = description
	}
}
```

The percentage signs are created by copying the URL. This is the original url `https://www.my-domain.de/suche?tx_solr[q]=*`

**Comment by dkd-kaehm** [comment] 2021-08-24 20:36
@Hobokens 
The TS path `plugin.tx_solr.index.` is for indexing part only, that does nothing with search component.

I'll close this issue. Please join TYPO3s Slack #ext-solr channel to get help with that trouble.

**Closed by dkd-kaehm** 2021-08-24 20:36 UTC
