### ISSUE TITLE
[FEATURE] StdWrap for tx_solr.search.targetPage

### ISSUE THREAD

**Issue by pduersteler** [TYPO3-Solr/ext-solr#2904] opened 2021-03-19 14:18 UTC
**Is your feature request related to a problem? Please describe.**
In certain cases, it would be really helpful to have stdWrap functionality for the targetPage setting to make it more dynamic or be able to adapt it.

**Describe the solution you'd like**
Classic stdWrap like e. g. a `typolink.parameter` has where you could call a userFunc to get the correct page uid for the search result page would be a really nice option. (Maybe I can find some time to submit a PR).

**Describe alternatives you've considered**
Dynamically setting a typoscript constant for this value, but this seems like a brittle idea.

**Additional context**
None

**Target versions**
Maybe in 11.0 or 11.1? I don't know.

**Comment by dkd-kaehm** [comment] 2021-03-19 14:35
@pduersteler 
This is a duplicate of #2712 .
I would propose to discuss this feature request in #2712.
Thanks for reporting. I'll close this in favor of first coming feature request.

**Closed by dkd-kaehm** 2021-03-19 14:35 UTC
