### ISSUE TITLE
[BUG] Exception thrown by Symfony PhpDocExtractor

### ISSUE THREAD

**Issue by spoonerWeb** [TYPO3-Solr/ext-solr#2580] opened 2020-04-21 18:47 UTC
**Describe the bug**
When visiting the page with the search form this exception is thrown:
`Call to undefined method phpDocumentor\Reflection\DocBlock\Tags\InvalidTag::getType()`

**To Reproduce**
1. Use TYPO3 v10
2. Use current master of Solr
3. Create a plugin with search form
4. Visit the page
5. See the exception

**Expected behavior**
No exception. ;)

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.0
 - Browser: any
 - EXT:solr Version: master (38e32cd) 
 - Used Apache Solr Version: 8.2.0
 - PHP Version: 7.4.4
 - MySQL Version: MariaDB 10.3.22

**Comment by dkd-kaehm** [comment] 2020-04-22 06:02
Closing due duplicate of #2573

**Closed by dkd-kaehm** 2020-04-22 06:02 UTC
