### ISSUE TITLE
[BUG] Setting page in foreign language to hidden, removes record from solr index in all languages

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#489] opened 2016-07-11 15:21 UTC
**Describe the bug**

Setting page in foreign language to hidden, removes record from solr index in all languages

**To Reproduce**

This test case uses https://github.com/TYPO3-Solr/solr-ddev-site

1. Translate page `Features` (UID: 84) to german and dansk
2. Set page with english (default) translation to hidden
3. Page will be removed from all cores: en, de, da

**Expected behavior**

The page should only be removed from core en

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4
 - Translation mode: connected
 - Browser: -
 - EXT:solr Version: dev-master (a18ab72a461a468a3a115defd83d78b982c105a6)
 - Used Apache Solr Version: -
 - PHP Version: -
 - MySQL Version: -

---

There is a bug on setting a page to hidden on multilanguage sites.

I am using TYPO3 4.5 with solr 2.7.1

Scenario:
-     there is a page in two languages: de and en, both are visible
-     set page in en to hidden
-     page will be removed from both de and en cores

https://forge.typo3.org/issues/41155

Todo: check if relevant in dev-master

**Comment by 3l73** [comment] 2021-03-05 11:31
The behaviour works as expected.

In case the editor deactivates a page with the default language, Solr removes even the translation from the cores.
This is not a bug, even TYPO3 itself deactivates the translations. 

In case the editor deactivates a translation of a page, i.e. german, Solr removes only this specific translation.

I suggest to close this issue since ext-solr behave as expected and the issue itself occured with ext-solr 2.7.

@dkd-kaehm @dkd-friedrich Any other ideas or suggestions?

**Comment by dkd-kaehm** [comment] 2021-03-05 11:33
agree

**Closed by dkd-kaehm** 2021-03-05 11:33 UTC
Labels: From Forge, bug
