### ISSUE TITLE
[BUG] Backend User gets logged out due to changes on pages with `l18n_cfg` field set to 1

### ISSUE THREAD

**Issue by DenisMir** [TYPO3-Solr/ext-solr#3246] opened 2022-04-22 07:13 UTC
**Describe the bug**
We found a major bug which breaks working with the TYPO3 backend. When you edit pages or add/edit records on pages that have `l18n_cfg` (`Hide default language of page`) set to `1` the backend user gets logged out.

The reason for it is the `RecordMonitor` that tries to add changed pages to the index queue. 

In this process it is checking for `ApacheSolrForTypo3\Solr\FrontendEnvironment->isAllowedPageType`. 

This leads to a initialisation of the `TSFE` with the important code lines being in `ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe->initializeTsfe` from line 191: 

```
            try {
                $tsfe->determineId($serverRequest);
                $serverRequest->withAttribute('frontend.controller', $tsfe);
                $tsfe->no_cache = false;
                $tsfe->getConfigArray($serverRequest);

                $tsfe->newCObj($serverRequest);
                $tsfe->absRefPrefix = self::getAbsRefPrefixFromTSFE($tsfe);
                $tsfe->calculateLinkVars([]);

                $beUser = $context->getAspect('backend.user');
                $loggedIn = $beUser->isLoggedIn();
            } catch (Throwable $exception) {
                // @todo: logging
                $this->serverRequestCache[$cacheIdentifier] = null;
                $this->tsfeCache[$cacheIdentifier] = null;
                // Restore backend user, happens when initializeTsfe() is called from Backend context
                if ($backedUpBackendUser) {
                    $GLOBALS['BE_USER'] = $backedUpBackendUser;
                }
                $beUser = $context->getAspect('backend.user');
                $loggedIn = $beUser->isLoggedIn();
                return;
            }
```
The `$tsfe->determineId($serverRequest);` ends up in the `TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->settingLanguage` which checks for `$pageTranslationVisibility = new PageTranslationVisibility((int)($this->page['l18n_cfg'] ?? 0));` and then ends up here: 

```
        // If default language is not available:
        if ((!$languageAspect->getContentId() || !$languageAspect->getId())
            && $pageTranslationVisibility->shouldBeHiddenInDefaultLanguage()
        ) {
            $message = 'Page is not available in default language.';
            $response = GeneralUtility::makeInstance(ErrorController::class)->pageNotFoundAction(
                $request,
                $message,
                ['code' => PageAccessFailureReasons::LANGUAGE_DEFAULT_NOT_AVAILABLE]
            );
            throw new PropagateResponseException($response, 1533931423);
        }
```

This 404 `PropagateResponseException` leads to the logout of the backend user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate `Hide default language of page` in page settings
2. Add a content element to this page
3. Backend user gets logged out

**Expected behavior**
Record monitoring should *never* lead to a logout of the backend user.

**Screenshots**
![Bildschirmfoto 2022-04-22 um 09 00 29](https://user-images.githubusercontent.com/157281/164621867-466c83c4-f7f0-4f8b-b602-648c3e7f9a0a.png)
![Bildschirmfoto 2022-04-22 um 09 03 14](https://user-images.githubusercontent.com/157281/164624420-729ca1b2-4af6-460e-ab43-94c1dc8c1e8b.png)

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.9
 - EXT:solr Version: 11.5.0-rc-1

**Comment by dkd-kaehm** [comment] 2022-04-22 08:33
Related change: c7c0ba8ad7a96e733d5dd73f2c5746bac95aee6f
@bmack do you have some suggestion for that issue?

**Comment by bmack** [comment] 2022-04-25 08:56
@dkd-kaehm Cannot reproduce this issue yet, but I have a similar problem in a 11.5.x-dev solr branch, which I cannot update yet to the latest RC-1 due to a missing PR being merged (fluid grouping).

In general, the exception should be caught, and the backend user should be kept, and if the exception is thrown the `$GLOBALs['BE_USER']` is empty but the `$backedUpBackendUser` is still available @DenisMir ?

**Comment by DenisMir** [comment] 2022-04-26 11:33
@bmack It is as you said `$GLOBALs['BE_USER']` is empty but `$backedUpBackendUser` is filled and ist seems to recover fine in the catch clause: 

<img width="1354" alt="Bildschirmfoto 2022-04-26 um 13 09 45" src="https://user-images.githubusercontent.com/157281/165289318-9cf82c4d-f253-451f-bc49-65f16b21823e.png">
<img width="1352" alt="Bildschirmfoto 2022-04-26 um 13 10 33" src="https://user-images.githubusercontent.com/157281/165289215-8c2c12c5-d2bf-4819-98a8-c7e8ff4193b8.png">
<img width="1173" alt="Bildschirmfoto 2022-04-26 um 13 19 23" src="https://user-images.githubusercontent.com/157281/165289274-2ec9c502-dfe9-420e-8d04-972c0b5ffee9.png">

I've added these `loggedIn` vars for debugging purposes. 

But when I step only one step further on to `ApacheSolrForTypo3\Solr\FrontendEnvironment\Tsfe->assureIsInitialized` after the ` $this->initializeTsfe($pageId, $language, $rootPageId);` call the `loggedIn` status suddenly turns false. 

<img width="1290" alt="Bildschirmfoto 2022-04-26 um 13 30 01" src="https://user-images.githubusercontent.com/157281/165290921-4cb081e5-83b8-4498-83a0-f5f5c370d5e3.png">

I don't get what is happening here but this leads to the logout.

**Comment by dkd-kaehm** [comment] 2022-07-15 14:43
@DenisMir 
Some updates on this issue? Do you have time to track to the source of trouble and fix this issue?

**Comment by dkd-kaehm** [comment] 2022-07-21 16:42
Can not reproduce this issue on [solr-ddev-site](https://github.com/TYPO3-Solr/solr-ddev-site/tree/release-11.5.x) within 
TYPO3 11.5.13 and EXT:solr 
at 3fa4ff49662a23fc75b02667823e9f1bded0f413 (dev-11.5 @ 2022.07.21)
Please ask to reopen this issue if some news or exact steps to reproduce this issue on solr-ddev-site are available.

**Comment by DenisMir** [comment] 2022-07-22 06:26
@dkd-kaehm I couldn't find the reason for the error. But I'm checking it now again on the `dev-11.5`.

**Comment by DenisMir** [comment] 2022-07-22 07:21
@dkd-kaehm Trying this on 11.5.13 + `dev-release-11.5.x 6196913` still results in the same error. Pages without `l18n_cfg` set do work and the other ones don't.

**Comment by dkd-kaehm** [comment] 2022-07-22 07:34
@DenisMir 
I'll reopen this issue.
Please try to reproduce within solr-ddev-site and provide exact steps to reproduce. 
Most probably fallback settings in site-config are player on this issue.

**Comment by DenisMir** [comment] 2022-07-22 07:44
@dkd-kaehm I'm setting up the ddev project right now. At the moment I'm a bit lost on why this happens. What I can also say is that `hidden = 1` on the page does remove the error (log out on adding/editing of CEs) as well although `l18n_cfg` keeps being set on `1`.

**Comment by DenisMir** [comment] 2022-07-28 10:54
@dkd-kaehm @bmack 

After a lot of testing I found out the source for the error. The reason for the error is the typo3 feature flag `subrequestPageErrors`. 

Here is the way to reproduce the error in the `solr-ddev-site` (https://github.com/TYPO3-Solr/solr-ddev-site) project. 

1) Add the error handler in the `Site` config
<img width="1542" alt="Bildschirmfoto 2022-07-28 um 12 44 53" src="https://user-images.githubusercontent.com/157281/181487336-0ddd0767-dcf7-46c8-9e4c-7383e26f7840.png">

2) Enable the feature `subrequestPageErrors`
<img width="785" alt="Bildschirmfoto 2022-07-28 um 12 45 15" src="https://user-images.githubusercontent.com/157281/181487465-ba1b5559-a786-45c4-ab0c-9d7bce9a3e55.png">

3) Set `l18n_cfg` of page `Features` to 1
<img width="742" alt="Bildschirmfoto 2022-07-28 um 12 47 08" src="https://user-images.githubusercontent.com/157281/181487655-c8460c16-6de5-4897-8d61-036618b19bbb.png">

4) Save -> get logged out instantly

So and now comes the weird thing and perhaps @bmack can shed some light on it. 

The docs for that feature in 11LTS says (https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.html)

```
The internal sub-request is the default behavior. This behavior can be disabled in favor of a curl-based approach by using the feature flag subrequestPageErrors in the Settings module.
```

And the changelog from 11LTS says (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-94402-GenerateErrorPagesViaTYPO3-internalSubRequest.html) 

```
This feature is disabled by default, as there are some cases where stateful information is not correctly reset for the subrequest. It may be enabled on an experimental basis via a feature flag called subrequestPageErrors in the "Settings" module.
```

But there is also a different issue regarding that feature: 

https://forge.typo3.org/issues/95253

And the description in the backend settings UI says

```
If on, error pages in the Frontend (such as 404 pages) will be requested internally via the TYPO3 Frontend instead of using an external HTTP request. It may be enabled on an experimental basis, as there are some cases where stateful information is not correctly reset for the subrequest. Disable this feature if you have trouble with stateful services or when some custom extensions overriding PHPs global variables.
Default setting: Disabled
```

So to be honest I'm 100% confused. What is the default behavior? Does it do the internal sub request by default or does it do the external curl call by default like in 10LTS. 

Nevertheless this is the reason for this bug.

**Comment by bmack** [comment] 2022-07-28 11:39
Yes. internal subrequests are "off by default".

**Comment by liayn** [comment] 2022-07-28 13:36
So https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/d71d1049439e8ffd888cabbef5e59d143ee8ab6f is the "offending" commit that introduced the wrong information in the docs as it seems. I'll follow-up on that.

**Comment by christophlehmann** [comment] 2023-10-17 09:40
Same here on v11.5.3. I get logged out when hiding a content element. 
I need the enabled subrequestPageErrors for a working referrer redirect in felogin, so my workaround is to use delayed updates
<img width="396" alt="delayed-updates" src="https://github.com/TYPO3-Solr/ext-solr/assets/4953689/f12fce3a-22d2-413c-a35c-b3675b8f857d">

**Comment by dkd-kaehm** [comment] 2024-11-29 18:51
We'll not fix that edge case anymore for EXT:solr versions <12.4 anymore.
Please use **"Delayed Mode"** suggested by [Christophs comment](https://github.com/TYPO3-Solr/ext-solr/issues/3246#issuecomment-1766050580)

**Closed by dkd-kaehm** 2024-11-29 18:51 UTC
