### ISSUE TITLE
[BUG] Bad suggest performance with TYPO3 10

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#2655] opened 2020-06-17 08:53 UTC
**Describe the bug**

The performance of the autosuggest on the TYPO3 10 system feels currently very bad (10sec on the dev system). We should analyze that also in combination with TYPO3 9 and check why it is much slower then before.

**To Reproduce**
1. Configure the autosuggest with the default template (Search (Example) - Suggest/autocomplete)

**Expected behavior**
Autosuggest should respond in milliseconds

**Comment by markuskobligk** [comment] 2020-07-09 12:27
Cannot reproduce this behaviour, the autosuggest is very fast for me on TYPO3 10.4.5 and EXT:solr 11.0.2, even though the Solr server runs on an external machine.

**Comment by dkd-kaehm** [comment] 2020-07-09 12:38
I think, this is on OsXs ddev environment only.

**Comment by markuskobligk** [comment] 2020-07-09 12:57
Ok, I can't test this, my computer ain't that fruity :)

**Comment by dkd-kaehm** [comment] 2021-05-10 13:40
Thanks for confirming Markus, i'll close this issue.

**Closed by dkd-kaehm** 2021-05-10 13:40 UTC
