### ISSUE TITLE
plugin.tx_solr.search.results.fragmentSize=2 no cropping highlighted text

### ISSUE THREAD

**Issue by timohund** [TYPO3-Solr/ext-solr#199] opened 2016-01-04 10:04 UTC
**Describe the bug**
If `plugin.tx_solr.search.results.resultsHighlighting.fragmentSize` is set e. g. to "2" I would expect the highlighted search-word to be only 2 chars long, but instead the whole search-word is highlighted.

**To Reproduce**

This test case based on project https://github.com/TYPO3-Solr/solr-ddev-site

1. Index all pages
2. Open the frontend and go to the search page
3. Search for `Form`

You should see a list of results with the term `Form` highlighted.

1. Within the backend open the template`Introduction Package`.
2. Add following line to the setup: `plugin.tx_solr.search.results.resultsHighlighting.fragmentSize = 2`
3. Save your changes
3. Go back to the search result and press 'Search'

You should see a list of results with the term `Form` highlighted. The difference is, that only the term and fragment separator is shown.

**Expected behavior**
Set `plugin.tx_solr.search.results.resultsHighlighting.fragmentSize` to 2 should reduce the search-word to be only 2 chars long.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.10
 - Browser: Chromium
 - EXT:solr Version: Master
 - Used Apache Solr Version: 8.5.2
 - PHP Version: 7.4
 - MySQL Version: 10.2

**Additional context**

From official Lucene documentation:
> Fragments are a portion of a document field that contains matches from the query and are sometimes also referred to as "snippets" or "passages".

> h1.fragsize
Specifies the approximate size, in characters, of fragments to consider for highlighting. The default is 100. Using 0 indicates that no fragmenting should be considered and the whole field value should be used.

-  https://lucene.apache.org/solr/guide/8_6/highlighting.html#common-highlighter-parameters

---

We need to check "plugin.tx_solr.search.results.fragmentSize" and check the generated solr query and why the text is not cropped. Is this a bug?

Lucas Marc 9:41 AM
> Hi
> Can anyone tell me what effect "plugin.tx_solr.search.results.fragmentSize" has?
>
> If I set it e. g. to "2" I would expect the highlighted search-word to be only 2 chars long, but instead the whole search-word is highlighted

Timo Schmidt 9:53 AM
> I think this is something different
> I would say this "fragmentSize" is the number of characters for the "window" that is used to show the highlighted words or the size of the "text fragment"

Lucas Marc 9:55 AM
> @timoschmidt: I don't quite understand what you mean with "window"

Timo Schmidt 9:56 AM
> https://wiki.apache.org/solr/HighlightingParameters#hl.fragsize

Lucas Marc 9:56 AM
> It says "The size, in characters, of the snippets (aka fragments) created by the highlighter". So I assume, that they mean: Number of characters, a fragment consists of

Timo Schmidt 9:57 AM
> I would say this is more or less the size of characters of the "context" where the highlighted word occures

Lucas Marc 9:57 AM
> Whereas a fragment is a highlighted word in the result
> What do you mean with "context"?
> The whole text, in which the searched word appears?
> What I don't understand is: If I set this setting to "2" something should be cropped. But I don't see any change in the search result

Timo Schmidt 10:00 AM
> Yes thats true
> But i would expected that the whole output is cropped
> Can you maybe analyze and debug what query is send to the solr server?

Lucas Marc 10:03 AM
> @timoschmidt: I did a debug on "class.tx_solr_pi_results.php" -> $query
> Do you mean that?

Timo Schmidt 10:05 AM
> Can you maybe send me the whole querystring?

Lucas Marc 10:06 AM
> It is NULL at this point

Timo Schmidt 10:07 AM
> Sorry i mean in Apache_Solr_Service->_sendRawGet
> The url that is send to solr

Lucas Marc 10:09 
> ok. just a second
> @timoschmidt: I post it in gist, otherwise it will blow up this irc
> @timoschmidt: https://gist.github.com/noahsmith1880/c3f1d2359014ca7cb6d9

Timo Schmidt 10:29 AM
> thx
> I'll created an issue for this on github and check it

Lucas Marc 10:30 AM
> @timoschmidt: So is it a bug?(edited)

Timo Schmidt 10:56 AM
> I need to check it

Lucas Marc 11:00 AM
> @timoschmidt: Ok. Can you give me the error report link so that I can see the result of your check?(edited)

**Comment by 3l73** [comment] 2021-01-07 14:02
Following arguments need to be checked:
- `hl.fragsizeIsMinimum`
- `hl.bs.type`

**Comment by 3l73** [comment] 2021-01-07 14:24
@dkd-kaehm As far I can see this is not a bug, more an expected behaviour.

The option `fragmentSize` defines the amount of characters that should be used for the text shown in the result.
This does not effect the term that is highlighted, what from my opinion is totally makes sense.

There for this issue is obsolet.

Did you have any thoughts about this topic?

**Comment by dkd-kaehm** [comment] 2021-01-20 11:46
Yep, the "fragsize" is the length of field contents to crop it to this value and not on the search term.
So I'll close this issue.
The fragsize with value of 2 makes no sense at all.
If somebody needs, must use the query-Modifier hook and set "fragsizeIsMinimum" to true.

**Closed by dkd-kaehm** 2021-01-20 11:46 UTC
