### ISSUE TITLE
[BUG] Guzzle not parsing content of pages

### ISSUE THREAD

**Issue by meridiumtechnologies** [TYPO3-Solr/ext-solr#2721] opened 2020-09-08 15:37 UTC
**Describe the bug**
Just updated from Solr 7.5.3 => 11.0.2 and it appears that the body of the pages of my multilang website are no longer being indexed (only the titles are). The error comes up on the **getUrlAndDecodeResponse** method as the **rawresponse === false**.

This is directly related to the implementation of Guzzle [in this commit](https://github.com/TYPO3-Solr/ext-solr/pull/1837/commits/9dee1d16b921ea33e7029673b60948472ae8f457) introduced in Solr 8.x.  More specifically the getUrl method replaced PHP _native file_get_contents_ with  Guzzle API call ( $this->requestFactory->request).

**Used versions**
 - TYPO3 Version: 9.5.19
 - Browser: all
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 2.4.46 (Unix) 
 - PHP Version: 7.2.33
 - MySQL Version: 5.6.23

**Additional context**
I used xdebug and there is not error message whatsoever thrown by Guzzle but the body of the page being parsed is systematically empty. I tested the same website with old and new versions of Solr in TYPO3 8LTS and TYPO3 9LTS respectively both in the exact same environment. Only the Guzzled version fails. I double checked Guzzle requirements.

**Comment by 3l73** [comment] 2020-09-08 15:46
Hi,

If you are using the Site Configuration, can you check what kind of protocol (http or https)  isin use?

Regards, 

Lars

**Comment by meridiumtechnologies** [comment] 2020-09-08 15:51
http

**Comment by 3l73** [comment] 2020-09-08 15:54
If you are open your website with a browser, does it open with http or https?

Just a guess, but I think, that this could be a reason.

**Comment by meridiumtechnologies** [comment] 2020-09-08 16:10
http all the way (development environment).

I can confirm that Sorl does crawl the webpages in the queue (apache logs) and the connection is fine (200). Yet, Guzzle's streaming/parsing returns an empty content (TYPO3SEARCH tags are there). The exact same content get indexed fine with Solr 7.x.

**Comment by 3l73** [comment] 2020-09-08 16:14
@dkd-kaehm any suggestions?

**Comment by meridiumtechnologies** [comment] 2020-09-08 18:55
I am not sure but the page seems to be parsed OK but the body of the page is being stored in field named tagsInLine (??).  Maybe it is the feeding to Solr that is deficient... Will continue to search.

**Comment by dkd-kaehm** [comment] 2020-09-09 06:58
@meridiumtechnologies 
Please consume our docs
https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.0/en-us/GettingStarted/ConfigureExtension.html#site-handling-recommended

EXT:solr 11.x requires the site configuration, the legacy mode was deprecated in EXT:Solr 10 and removed in EXT:Solr 11.
So you must use the site handling from TYPO3 or downgrade to EXT:Solr 10.

Especially following warning is important for site handling setups:

```
EXT:Solr needs a proper domain as base for the site. If the base is set to "/" or a similar relative path, the Indexing will throw an error, so please make sure that "base" is a fully qualified domain like "https://my.project.tld/"
```

You could consume our setup https://github.com/TYPO3-Solr/solr-ddev-site 
especially https://github.com/TYPO3-Solr/solr-ddev-site/blob/master/config/sites/solr-testsystem/config.yaml#L2 to find out what are the differences.

---

If you need help by identifying the source of this trouble, please use our `#ext-solr` TYPO3 Slack channel or contact us via solr-eb-support@dkd.de .

**Comment by meridiumtechnologies** [comment] 2020-09-09 12:06
All doc was consumed. I am using the new site configuration indeed and the base domain is resolving properly.

**Comment by martinschoene** [comment] 2020-09-10 08:53
hi, 
I am facing the same Problem. 
The only difference is that I am using TYPO3 10.

addionally i can tell that indexing news works fine.

I only get the error on pages.

greetings
martin

**Comment by dkd-kaehm** [comment] 2020-09-10 10:10
I can't reproduce the issue.
Are the pages access restricted?
Could you try to reproduce the behavior on our https://github.com/TYPO3-Solr/solr-ddev-site ?

**Comment by rafu1987** [comment] 2020-09-15 17:56
I have this error as well with detail pages of custom extensions.

TYPO3 10.4.6
solr 11.0.2

**Comment by dkd-kaehm** [comment] 2020-09-16 06:05
> I have this error as well with detail pages of custom extensions.
> 
> TYPO3 10.4.6
> solr 11.0.2
> 
> **EDIT:**
> I now added the "Do not include in search" checkbox for the detail pages and the errors are gone, although I configured my extension, to not throw an error, if no arguments are set.
> 
> Mentioned here:
> https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.0/en-us/Backend/IndexQueue.html#custom-records-links-and-detail-page

Those are [USER_INTs](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/ContentObjects/UserAndUserInt/Index.html#user-and-user-int). 
IThere is something other by @meridiumtechnologies  and @martinschoene? All pages are affected or just some with USER_INTS(Plugins & co.)?

**Comment by meridiumtechnologies** [comment] 2020-09-16 15:13
90% of the pages are affected and I can't find the pattern.

The typical response I am getting from Solr (Guzzle) during the indexation is:

` {"request ID":"5f6224bd35c46","request url":"http://mydomain/mypage.html","request headers":["User-Agent: TYPO3","X-Tx-Solr-Iq: {\"requestId\":\"5f6224bd35c46\",\"item\":177578,\"page\":893,\"actions\":\"indexPage\",\"hash\":\"faddbd1e245163a7b9d5b983b9693012\",\"loggingEnabled\":\"1\",\"accessRootline\":\"c:0\"}"],"response headers":{"Date":["Wed, 16 Sep 2020 14:44:13 GMT"],"Server":["Apache/2.4.46 (Unix) PHP/7.2.33"],"X-Powered-By":["PHP/7.2.33"],"Content-Length":["0"],"Content-Type":["application/json"]},"raw response body":""}`

The interesting part is the end of the response header:

`"Content-Length":["0"],"Content-Type":["application/json"]},"raw response body":""`

It is the empty **body** in the response that is causing the issue (these pages all respond fine in the browser).

I must admit it sounds like and environment issue (I have seen OSX singularities before) but I can't figure it out.  My settings are standards.   Everything is resolving fine, I have curl and all other apache/php basic modules (I think). It is as if the content stream gets corrupted (charset issue? I am all utf-8).

I have looked everywhere and I am starting to get obsessed . Any suggestions?

**Comment by dkd-kaehm** [comment] 2020-09-17 06:17
> I have looked everywhere and I am starting to get obsessed . Any suggestions?

I have two currently:

1. The pages are access restricted -> please try the branch from #2695 https://github.com/dkd-kaehm/ext-solr/tree/feature/2634_protected-pages
2. The pages have some chars, which break the string see #2617
  Though I couldn't reproduce that on our linux setups, it was on Windows machine only, but nevertheless it could be the reason.

**Comment by meridiumtechnologies** [comment] 2020-09-17 14:14
After many hours of debugging, it appears that the temporary solution posted in issue #2617 is definitely alleviating this problem (i.e. the content of the pages is finally picked up and indexed, with the exception of the " à " character that disappears into thin air).  For future references, this is my dev environment:

- **PHP:**  7.2 (same issue with PHP 7.4)
- **cUrl::** 7.72.0
- **OS:** OSX 10.5.6 (Catalina)
- **LAMP** components built with brew.

Let me know if you need more information.

**Comment by dkd-kaehm** [comment] 2020-09-17 15:22
Seems to be some lib issue used by Osx and Windows.

**Comment by IvanovArtur** [comment] 2020-09-23 08:26
Had very similar issue. I fixed it by adding `config.index_enable = 1` in TypoScript

**Comment by dkd-kaehm** [comment] 2021-06-25 14:22
I'll close this issue in favour of #2617

**Closed by dkd-kaehm** 2021-06-25 14:22 UTC
Labels: bug, more-information-needed
