### ISSUE TITLE
locallangXMLOverride don't work correctly in Templates

### ISSUE THREAD

**Issue by FlorianEngelke** [TYPO3-Solr/ext-solr#26] opened 2015-06-29 14:05 UTC
Hey. i found a bug.
The feature to override an XML file don't work in Template.

$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:solr/Resources/Private/Language/PluginResults.xml'][] = 'EXT:test/Resources/Private/Extensions/Solr/Language/PluginResults.xml';

All marker with ###LLL:...### became the wrong XML file. 
All marker handled with PHP ( ###RESULTS.SEARCHED_FOR### ) are fine.

![solr-lll](https://cloud.githubusercontent.com/assets/1029374/8409519/b4c0a22e-1e78-11e5-829f-1c13fba0812e.jpg)

typo3conf/ext/solr/Classes/PluginBase/PluginBase.php

$template->addViewHelper('LLL', array(
            'languageFile' => $GLOBALS['PATH_solr'] .'Resources/Private/Language/' . str_replace('Pi', 'Plugin', $this->getPluginKey()) . '.xml',
            'llKey'        => $this->LLkey
        ));
I know that I can handle this with TypoScript but there are some problems with file encoding and turkish chars.

**Comment by irnnr** [comment] 2015-06-29 19:37
What TYPO3 version, what extension version are you using?

**Comment by irnnr** [comment] 2015-07-13 16:28
bump @FlorianEngelke, any feedback?

**Comment by irnnr** [comment] 2015-08-01 19:45
closing for no feedback, feel free to re-open once you can provide needed feedabck

**Comment by syssi** [comment] 2015-08-11 15:28
I can confirm this issue. I'm using solr 3.0.1. I have added this line to my AdditionalConfiguration.php of TYPO3 6.2: 

```php
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:solr/Resources/Private/Language/PluginResults.xml'][] = 'fileadmin/default/extensions/solr/Resources/Private/Language/PluginResults.xml';
```
The PluginResults.xml is just a copy of the origin file. I can change the value of key "results_range" but changing the submit-button label does not work f.e.

**Comment by s-nunez-gosub** [comment] 2015-09-04 12:19
It works for me with TYPO3 6.2:

I have added to AdditionalConfiguration.php:

$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:solr/Resources/Private/Language/PluginResults.xml'][] = 'EXT:my_extension/Resources/Private/Language/PluginResults.xml';

And the translations will be overridden.

**Comment by astehlik** [comment] 2015-10-15 08:12
Can this change please be reverted? It is not needed IMO and it breaks merging of exising language files and override labels. Currently you need to copy **all** labels in the override file which is quite unhandy.

I think the problem lies in the configuration. The ```EXT:``` prefix is already resolved in the LLL view helper. This is why you need to use the absolute filename in your override config:

```
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['/var/www/mywebroot/typo3conf/ext/solr/Resources/Private/Language/PluginResults.xml'][] = 'EXT:my_extension/Resources/Private/Language/PluginResults.xml';
```

Overriding works perfectly (at least in TYPO3 6.2) when I use the absolute path in my config and remove the ```overrideLocalLangFile()``` code from the LLL view helper.

**Comment by irnnr** [comment] 2015-10-16 14:18
According to the docs the key is not an absolute path, but uses the `EXT:` notation: https://docs.typo3.org/typo3cms/CoreApiReference/Internationalization/Translation/Index.html#xliff-translating-custom

**Comment by irnnr** [comment] 2015-10-16 14:19
re-opening for discussion

**Comment by astehlik** [comment] 2015-10-16 15:31
The problem ist how ```GeneralUtility::readLLfile()``` is called in the ```Lll``` view helper.

The view helper is registered in ```PluginBase::initializeTemplateEngine()```:

```
$template->addViewHelperIncludePath($this->extKey, 'Classes/ViewHelper/');
$template->addViewHelper('LLL', array(
	'languageFile' => $GLOBALS['PATH_solr'] .'Resources/Private/Language/' . str_replace('Pi', 'Plugin', $this->getPluginKey()) . '.xml',
	'llKey'        => $this->LLkey
));
```

The variable ```$GLOBALS['PATH_solr']``` already contains the resolved Extension path and not ```EXT:solr/...```.

This is why the override mechanism will only work when you use the absolute filename.

**Comment by irnnr** [comment] 2015-10-16 16:38
ah ok, then let's fix the root, not the symptom!

**Closed** 2015-10-16 16:57 UTC
Labels: needs feedback
