### ISSUE TITLE
[Bug] In a recursive SOLR_RELATION only one element from tt_content gets indexed into the solr core

### ISSUE THREAD

**Issue by haraldwitt** [TYPO3-Solr/ext-solr#2743] opened 2020-10-07 09:19 UTC
I have a custom table "offers" which contains a field "product_uid" pointing to the product table.
I have the other custom table "products" with the field "content_elements" pointing to tt_content. 
"content_elements" is an inline element in the same manner tx_news it does.
Now I want to index the content elements as SOLR_CONTENT with an indexing configuration for "offers". Why that? The reason is, that "offers" contains an endtime-field which is very important for the search results!
My index configuration looks as follows:
```
plugin.tx_solr.index.queue {
	offers = 1
	offers {
		table = offers
		fields {
			...
			content = SOLR_CONTENT
			content.cObject = COA
			content.cObject {
				20 = SOLR_RELATION
				20 {
					localField = product_uid
					foreignLabelField = content_elements.bodytext
					singleValueGlue = | |
				}
			}
			...
		}
	}
}
```
Using this, only the bodytext of the LAST related record of tt_content will appear in the content-field of the solr core_de.

But when indexing "products", the bodytext of ALL related records will be found in the solr core_de.
The configuration for products:
```
plugin.tx_solr.index.queue {
	products = 1
	products {
		table = products
		fields {
			...
			content = SOLR_CONTENT
			content {
				cObject = COA
				cObject {
					10 = SOLR_RELATION
					10 {
						localField = content_elements
						foreignLabelField = bodytext
						singleValueGlue = | |
					}
				}
			}
			...
		}
	}
}
```
But this is not suittable for me because of the missing endtime-field in products.

**Comment by haraldwitt** [comment] 2020-10-07 09:47
Ok, I found, this is duplicate to issue #2147
https://github.com/TYPO3-Solr/ext-solr/pull/2147

**Comment by haraldwitt** [comment] 2020-10-07 13:11
Ok, I got it!

Class:	ApacheSolrForTypo3\Solr\ContentObject\Relation
Line 	325++
Method:	resolveRelatedValue

There you con find the following:
            // recursion
            $relatedItemsFromForeignTable = $this->getRelatedItemsFromForeignTable(
                $foreignTableName,
                $relatedRecord['uid'],
                $foreignTableTca['columns'][$foreignTableLabelField],
                $parentContentObject
            );
            $value = array_pop($relatedItemsFromForeignTable);

Obviously the array_pop() makes the problem. 
I replaced array_pop()-line with the following:
            $singleValueGlue = !empty($this->configuration['singleValueGlue']) ? trim($this->configuration['singleValueGlue'], '|') : ', ';
            $value = implode($singleValueGlue, $relatedItemsFromForeignTable);

And now all functions as expected!
Hope this Bugfix will be accepted by Ingo :-)

**Comment by haraldwitt** [comment] 2020-10-08 07:06
The better way is to respect also the multiValue parameter of SOLR_RELATION:
...
	if (empty($this->configuration['multiValue'])) {
		// single value, need to concatenate related items
		$singleValueGlue = !empty($this->configuration['singleValueGlue']) ? trim($this->configuration['singleValueGlue'], '|') : ', ';
		$value = implode($singleValueGlue, $relatedItemsFromForeignTable);
	} else {
		// multi value, need to serialize as content objects must return strings
		$value = serialize($relatedItemsFromForeignTable);
	}
...
Greetings
Harald

**Comment by dkd-kaehm** [comment] 2020-10-08 07:56
@haraldwitt thanks for reporting this issue.
Could you please provide a Pull-Request?
Wee need a tests to reproduce this, could you please provide the test case or at least the fixture?

**Comment by haraldwitt** [comment] 2020-10-08 13:05
Hi @dkd-kaehm,
now I've created a Pull-Request. But I haven't a clue on how to write a test or a fixture :-(

**Comment by dkd-kaehm** [comment] 2020-10-09 12:35
@haraldwitt 
Thanks for PR.
We'll provide a tests for this case.

**Comment by toco3** [comment] 2020-10-17 18:32
I had the same issue:

I have a model "section" with an inline relation to recipe. The "recipe" model has an inline relation to ingredient:

section -> recipe -> ingredient

without the bugfix this does not work:

`    section {
        additionalPageIds = 123
        table = tx_toco3ext_domain_model_section
        fields {
....
            content = SOLR_CONTENT
            content {
                cObject = COA
                cObject {`
                    120 = SOLR_RELATION
                    120 {
                        localField = recipe
                        foreignLabelField = ingredients.ingredient.title
                    }
          }
   }
}`

I get only one in ingredient! 
but if I start one level "deeper" it works:
`    recipe {
        additionalPageIds = 123
        table = tx_toco3ext_domain_model_recipe
        fields {

            content = SOLR_CONTENT
            content {
                cObject = COA
                cObject {

                    10 = SOLR_RELATION
                    10{
                        localField = ingredients
                        foreignLabelField = ingredient.title
                        multiValue = 1
                    }
                }
            }

        }`

here I get all ingredients.

After applying your Bugfix the first code also returns all ingredients!!

**Comment by dkd-kaehm** [comment] 2021-01-22 17:37
@toco3 and @haraldwitt please checkout the latest state and give a feedback.
We want integration test cases for this PR anyway.

**Comment by dkd-kaehm** [comment] 2023-10-13 16:10
@haraldwitt FYI Your #2745 pull request is gone, because of fork deletion.

**Comment by dkd-kaehm** [comment] 2023-10-13 16:11
@haraldwitt, @cehret
 This issue is most probably fixed by #3484 for TYPO3 11.5 and by #3475 for TYPO3 12.4.
 Please confirm the functionality.

**Comment by haraldwitt** [comment] 2023-10-16 07:05
@dkd-kaehm
Oh, I'm sorry. I totally forgot this 3 year old PR. But I'll check this issue in 11.5 again.

**Comment by dkd-kaehm** [comment] 2023-10-19 06:49
@haraldwitt Top.

**Closed by dkd-kaehm** 2023-10-19 06:49 UTC
