### ISSUE TITLE
[BUG] TS setting "availableTemplates" not working when declared outside root site page

### ISSUE THREAD

**Issue by TechnoQuebecca** [TYPO3-Solr/ext-solr#3759] opened 2023-08-15 13:37 UTC
**Describe the bug**
plugin.tx_solr.view.templateFiles.results.availableTemplates only works when declared on the site root page.

**To Reproduce**
0. Connect to BE 
1. Go to a sub page root/my-sub-page (uid = 2)
2. Set the following TS on page template on my-sub-page 
```
plugin.tx_solr {
    view {
        templateFiles.results.availableTemplates {
            myTemplate {
                label = My template
                file = my-template.html
            }
        }
    }
}
```
3. insert solr_pi_results plugin into my-sub-page 
4. Assert that option "My template" is not added to the "Custom Template" select field in the plugin flexform.
5. Move the TS on point 2 to root page uid = 1
6. Assert that option "My template" is now added in the plugin on my-sub-page

**Expected behavior**

Putting the TS on my-sub-page should make the "My template" option be added in the field.

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.30
 - EXT:solr Version: 11.5.2

** Additionnal information **

I think this bug affects every TS plugin configuration since tx_solr relies on TYPO3 api to fetch configuration, but in BE context, TYPO3 is unable to detect the current page uid, and only fetch the root page TS configuration as a fallback.

Maybe the userFunc ApacheSolrForTypo3\Solr\System\UserFunctions\FlexFormUserFunctions->getAvailableFunctions() should initialize a complete $GLOBAL[TSFE] as a workaround to fix TYPO3 configuration api in BE context.

**Comment by dkd-kaehm** [comment] 2023-08-15 19:07
@TechnoQuebecca Thanks for reporting that issue.

That is not a bug of EXT:solr, but current and expected behavior in TYPO3 core. 
Our current implementation: merged by #3496 -> https://github.com/TYPO3-Solr/ext-solr/pull/3496/commits/a7e3b201ceae31e90fef62d95c488d046b02b504

https://github.com/TYPO3-Solr/ext-solr/blob/3276728eeec729578c9a3100b7e6acc517930238/Classes/System/UserFunctions/FlexFormUserFunctions.php#L187-L197

The following doc-block from [TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager::getCurrentPageId()](
https://github.com/TYPO3/typo3/blob/c655ff1147144bfb9b3ba66fd9efda46f643f8f3/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php#L309-L330) describes how it behaves:

```
   /**
     * The full madness to guess a page id:
     * - First try to get one from the request, accessing POST / GET 'id'
     * - else, fetch the first page in page tree that has 'is_siteroot' set
     * - else, fetch the first sys_template record that has 'root' flag set, and use its pid
     * - else, 0, indicating "there are no 'is_siteroot' pages and no sys_template 'root' records"
     *
     * @return int current page id. If no page is selected current root page id is returned
     */
```

---

**Please make sure that right one of fallback chain links is fulfilled to use custom templates in sub-trees.**

**Closed by dkd-kaehm** 2023-08-15 19:07 UTC

**Comment by cbaur** [comment] 2024-07-30 12:33
Just in case anyone stumbles upon this in the future: I just experienced that it is necessary to set the configuration in **each and every** sys_template root record (when working with a multisite instance). The reason for that is that TYPO3 retrieves:

```
 - else, fetch the first page in page tree that has 'is_siteroot' set
 - else, fetch the first sys_template record that has 'root' flag set, and use its pid
```

and therefore you cannot be sure that the record retrieved is the root template of your current page. This also means that this feature is not really multisite compatible as you cannot have different settings in different page trees.

@dkd-kaehm as an idea for future releases, wouldn't it be an option to extend the flexform in another way, probably like in https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/ExtendNews/ExtendFlexforms/Index.html ?

**Comment by dkd-kaehm** [comment] 2024-07-30 15:42
> Just in case anyone stumbles upon this in the future: I just experienced that it is necessary to set the configuration in **each and every** sys_template root record (when working with a multisite instance). The reason for that is that TYPO3 retrieves:
> 
> ```
>  - else, fetch the first page in page tree that has 'is_siteroot' set
>  - else, fetch the first sys_template record that has 'root' flag set, and use its pid
> ```
> 
> and therefore you cannot be sure that the record retrieved is the root template of your current page. This also means that this feature is not really multisite compatible as you cannot have different settings in different page trees.
> 
> @dkd-kaehm as an idea for future releases, wouldn't it be an option to extend the flexform in another way, probably like in https://docs.typo3.org/p/georgringer/news/main/en-us/Tutorials/ExtendNews/ExtendFlexforms/Index.html ?

Please create a issue for that feature request.
