### ISSUE TITLE
[BUG] Required solr connection property port is missing

### ISSUE THREAD

**Issue by rrohaczek** [TYPO3-Solr/ext-solr#3855] opened 2023-10-31 14:20 UTC
**Problem**
When i submit the search form in the frontend, the error message: "Required solr connection property port is missing" appears - despite the site config is defined like this: 

config.yaml
solr_port_read: '%env(SOLR_PORT)%'
solr_port_write: '%env(SOLR_PORT)%'

.htaccess
SetEnv SOLR_PORT 8983

The error message / problem occurs regularly. I already set the value directly in the site config but it did not change anything.

**Screenshots**
![Solr-TYPO3 Exception](https://github.com/TYPO3-Solr/ext-solr/assets/8190586/a723913c-e1b9-424a-9dc2-6fd21245aa31)

**Used versions:**
 - TYPO3 Version: 11.5.32
 - EXT:solr Version: 11.5.3
 - Used Apache Solr Version: 8.11.2
 - PHP Version: 7.433
 - MySQL Version: 5.7.41

**Comment by dkd-kaehm** [comment] 2023-10-31 15:15
Please use the [helhum/dotenv-connector](https://github.com/helhum/dotenv-connector) integration for TYPO3 and an environment file.

This should work, I'll close this issue. But we can reopen it anytime.

**Closed by dkd-kaehm** 2023-10-31 15:15 UTC

**Comment by rrohaczek** [comment] 2023-10-31 15:25
As written in the bug report: I already set the value (without %env(SOLR_PORT)%') directly in the site config but it did not change anything.

**Comment by dkd-kaehm** [comment] 2023-11-01 07:13
On any change of site config values you want to flush the caches via Maintenance module.

**Comment by rrohaczek** [comment] 2023-11-20 14:13
I usually clear the cache when i change something in the site config. The problem still occurs with the newest EXT:solr v11.5.5. What else information is useful for you?

**Comment by dkd-kaehm** [comment] 2024-01-16 12:59
@simplychrislike @rrohaczek 
We can not reproduce the issue. Please debug and find the cause of this trouble.
May be we can add this infos to the FAQ.

**Comment by simplychrislike** [comment] 2024-01-17 09:19
I get the error message when uploading a file in the Filelist module and also in the File Index Queue. Now that I have removed apache-solr-for-typo3/tika: 11.0.1, the error message no longer appears. I'm wondering if I even need tika because for now it seems like solrfal does the job?!

**Comment by dkd-kaehm** [comment] 2024-01-17 10:26
> I get the error message when uploading a file in the Filelist module and also in the File Index Queue. Now that I have removed apache-solr-for-typo3/tika: 11.0.1, the error message no longer appears. I'm wondering if I even need tika because for now it seems like solrfal does the job?!

We'll test that scenario.
@rrohaczek Is EXT:tika installed in your system?
@simplychrislike which service type is configured for EXT:tika?

**Comment by dkd-kaehm** [comment] 2024-01-17 10:48
> No, i don't have EXT:tika installed. Back in october '23 i could not determine what the reason for the problem was.

Does it now work?

**Comment by simplychrislike** [comment] 2024-01-17 13:58
This is my tika config:

```
  // I've set these - same as for the solr-extension
    extractor = solr
    solrHost = myprojectrelatedhost.com
    solrPath = /
    solrPort = 8983
    solrScheme = http

  // These have default values
    excludeMimeTypes =
    fileSizeLimit = 500
    javaCommandOptions =
    logging = 1
    showTikaSolrModule = 0
    tikaPath =
    tikaServerHost = localhost
    tikaServerPath =
    tikaServerPort = 9998
    tikaServerScheme = http
```

In the Reports module at the bottom for Apache Tika it says

> Configuration Incomplete
> Could not extract file contents with Solr Cell.
