### ISSUE TITLE
Missing  Custom Template  when  Extend to Subpages = 1 

### ISSUE THREAD

**Issue by drblitz-weblab** [TYPO3-Solr/ext-solr#3420] opened 2022-12-07 09:31 UTC
1. For testing you can add this code to your root page

```
plugin.tx_solr.view.templateFiles.results.availableTemplates {
    resultss = Results
    default {
        label = Default Searchresults Template
        file = Results
    }
    finder {
        label = Event
        file = ProductFinder
    }
}
```
And here is working fine 
<img width="978" alt="Zrzut ekranu 2022-12-7 o 10 25 44" src="https://user-images.githubusercontent.com/44512564/206140195-d9f3571c-5e68-4206-b46c-fc7a2b4e473a.png">

2. Create two example pages  and set in page property  Extend to Subpages = 1 
<img width="2017" alt="Zrzut ekranu 2022-12-7 o 10 28 32" src="https://user-images.githubusercontent.com/44512564/206140828-2d9622f6-0e22-4584-9eb9-fe8f8e9d041c.png">

the page tree should look like this

<img width="249" alt="Zrzut ekranu 2022-12-7 o 10 29 37" src="https://user-images.githubusercontent.com/44512564/206141128-0149849f-78f1-4497-bd98-ecbf80b73bf6.png">

3.  Go to page "Sub 2.1" and add solr search 
<img width="1885" alt="Zrzut ekranu 2022-12-7 o 10 30 59" src="https://user-images.githubusercontent.com/44512564/206141453-f6441adc-1f24-4cec-b7cf-8dfe588114ed.png">

**Custom template is missing**

**Used versions (please complete the following information):**
 - TYPO3 Version: 11.5.19
 - EXT:solr Version: 11.5.0
 - PHP Version: 8.0

**Comment by micron** [comment] 2022-12-13 19:51
Just ran into this issue too. Any estimate when this will be fixed ?

**Comment by dkd-kaehm** [comment] 2022-12-19 08:32
@drblitz-weblab @micron 
Thanks for reporting and confirming that issue.
That is very strange behavior. We want to find out the cause of that issue. 
If you find something, please make notice there.

**Comment by sabbelasichon** [comment] 2023-02-10 12:26
@dkd-kaehm The thing is that the retrieval for the templates uses the FrontendEnvironment class but the page is access restricted so the template configuration cannot be fetched and nothing is found.

**Comment by sabbelasichon** [comment] 2023-02-10 14:31
@dkd-kaehm I am not sure why the plugin configurations are using the simulated frontend environment. Maybe i am missing something here.

**Comment by dkd-kaehm** [comment] 2023-02-10 15:57
> @dkd-kaehm I am not sure why the plugin configurations are using the simulated frontend environment. Maybe i am missing something here.

Yes, nice catch. 
@sabbelasichon Thanks for fixing that issue.
This was most probably copy/paste trouble from other EXT:solr components on adding this feature.

@drblitz-weblab @micron
Could you please test this patch and approve the #3486?

**Comment by drblitz-weblab** [comment] 2023-02-19 20:52
hello @dkd-kaehm thx you for this patch, works

**Closed** 2023-03-02 15:54 UTC
