### ISSUE TITLE
[BUG] Duplicate entries in the index queue with mount points

### ISSUE THREAD

**Issue by dmitryd** [TYPO3-Solr/ext-solr#715] opened 2016-11-01 14:33 UTC
If you use mount points, you may get a lot of duplicates in the `tx_index_queue_item` table due to the code in `Classes/IndexQueue/Initializer/Page.php`:

```php
    protected function addMountedPagesToIndexQueue(
        array $mountedPages,
        array $mountProperties
    ) {
        $mountIdentifier = $this->getMountPointIdentifier($mountProperties);
        $initializationQuery = 'INSERT INTO tx_solr_indexqueue_item (root, item_type, item_uid, indexing_configuration, indexing_priority, changed, has_indexing_properties, pages_mountidentifier, errors) '
            . $this->buildSelectStatement() . ', 1, ' . $GLOBALS['TYPO3_DB']->fullQuoteStr($mountIdentifier,
                'tx_solr_indexqueue_item') . ',""'
            . 'FROM pages '
            . 'WHERE '
            . 'uid IN(' . implode(',', $mountedPages) . ') '
            . $this->buildTcaWhereClause()
            . $this->buildUserWhereClause();
        $GLOBALS['TYPO3_DB']->sql_query($initializationQuery);
        $this->logInitialization($initializationQuery);
    }
```

This code is called multiple times even if you save a content element once. New items are inserted without checks that they are already there. I had 201 of them and after a couple of saves I got 356 of them:

```sql
MariaDB [***local]> select item_type,item_uid,count(*) as c from tx_solr_indexqueue_item group by item_type,item_uid having count(*)>1 order by c desc limit 10;
+-----------+----------+-----+
| item_type | item_uid | c   |
+-----------+----------+-----+
| pages     |      886 | 856 |
| pages     |      889 | 356 |
| pages     |      880 | 181 |
| pages     |      714 |   6 |
| pages     |      715 |   6 |
| pages     |      861 |   2 |
| pages     |      863 |   2 |
| pages     |      865 |   2 |
| pages     |      867 |   2 |
| pages     |      869 |   2 |
+-----------+----------+-----+
10 rows in set (0.00 sec)
```

Now if you try to delete something on that page, garbage collection kicks and tries to send 356*5 (by amount of languages in this instalation) `delete` requests to solr server. Each such request is followed by a solr commit. It never completes due to the server timeout.

TYPO3 6.2, solr 3.0.1 but the code is the same in the current version of solr on github.

**Comment by timohund** [comment] 2016-11-01 14:44
@dmitryd Thanks for your bug report. Just by reading it looks to me that a check is missing if an queue entry allready exists. We should a an integration tests that verfies that queue entries will not be created multiple times. Can you investiage it can create a pull request?

**Comment by dmitryd** [comment] 2016-11-02 08:17
May be later (no time now). For our project I made an XCLASS. It can be used as a base for the fix:

```php
<?php
namespace Snowflake\Sfpextendersolr\Xclass;
/***************************************************************
*  Copyright notice
*
*  (c) 2016 snowflake productions gmbh <support@snowflake.ch>
*  All rights reserved
*
*  This script is part of the TYPO3 project. The TYPO3 project is
*  free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  The GNU General Public License can be found at
*  http://www.gnu.org/copyleft/gpl.html.
*
*  This script is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  This copyright notice MUST APPEAR in all copies of the script!
***************************************************************/

class PageInitializer extends \Tx_Solr_IndexQueue_Initializer_Page {
	/**
	 * Adds the virtual / mounted pages to the Index Queue as if they would
	 * belong to the same site where they are mounted.
	 *
	 * @param array $mountedPages An array of mounted page IDs
	 */
	protected function addMountedPagesToIndexQueue(array $mountedPages) {
		$rows = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows('COUNT(*) AS c,item_uid', 'tx_solr_indexqueue_item', 'item_type=\'pages\' AND item_uid IN (' . implode(',', $mountedPages) . ')',
			'', '', '', 'item_uid'
		);
		foreach ($mountedPages as $key => $pageUid) {
			if ($rows[$pageUid]['c'] > 0) {
				unset($mountedPages[$key]);
			}
		}
		if (count($mountedPages) > 0) {
			parent::addMountedPagesToIndexQueue($mountedPages);
		}
	}

}
```

**Comment by timohund** [comment] 2016-11-02 08:53
@dmitryd Thx for sharing your fix. I'll have a look on it.

**Comment by timohund** [comment] 2016-11-09 13:19
@dmitryd Thx for the bug report! I've adapted you patch and added tests and created a pull request. Can you maybe check and confirm that the problem is resolved on your system as well?

**Comment by timohund** [comment] 2016-11-10 09:29
I've merged the pull request. If you have any issues, please open a new issue.

**Closed** 2016-11-10 09:28 UTC
Labels: bug
