### ISSUE TITLE
[TASK] Update documentation to not that config.index_enable is still needed in TS setup

### ISSUE THREAD

**Issue by Tuurlijk** [TYPO3-Solr/ext-solr#2730] opened 2020-09-18 10:21 UTC
The latest docs do not state that `config.index_enable = 1` is still needed in TypoScript setup.

I am building a new site without any prior config. I followed the manual to the letter and could not get the pages to index.

Failure message was: `1319116885: RuntimeException: Failed to execute Page Indexer Request. See log for details.`

Running TYPO3 10 with site config.yml and all fields filled in according to the manual. 10 languages.

**Comment by dkd-kaehm** [comment] 2020-09-21 07:53
Closing it, because a duplicate of #2523

**Closed by dkd-kaehm** 2020-09-21 07:53 UTC
