### ISSUE TITLE
[BUG] Composer dependencies of solarium client

### ISSUE THREAD

**Issue by mschwemer** [TYPO3-Solr/ext-solr#2574] opened 2020-04-20 14:05 UTC
In the composer dependencies the solarium client is "fixed" a version `~4.2.0`. This version has a dependency to the `symfony/event-dispatcher` versions `^2.7 || ^3.0 || ^4.0`, but TYPO3 has a dependency to version `5.0.7` (via the `symfony/console`).

So it is not possible to install EXT:solr.

**Solution:** Upgrade to `solarium/solarium` in version `^5.2.0`.

TYPO3 Version: TYPO3 10.4-dev (aka master)
EXT:solr Version: mastern

**Update**

Using solarium v5.2.0 is no solution as it has breaking changes (other than requiring another php version). 

The solution is to require `symfony/console` in version `^4.4` explicitly in your projects composer.json.

**Comment by georgringer** [comment] 2020-05-19 08:57
@mschwemer you can also just use `"symfony/event-dispatcher":"^4"  in your root composer.json.

solarium allowed version 5 of symfony/event-dispatcher with version 5.1.5 (see https://github.com/solariumphp/solarium/blob/5.1.5/composer.json)

**Comment by pschirch** [comment] 2020-06-11 11:15
@mschwemer @georgringer @dkd-kaehm @Freshmeat-ch

None of the suggested workarounds in #2574 and #2632 resolves this issue. So this current extension release can not be installed successfully in a fresh TYPO3 10 installation. This is very frustrating and needs more attention for a stable version.

**Comment by dkd-kaehm** [comment] 2020-06-15 09:23
> @mschwemer @georgringer @dkd-kaehm @Freshmeat-ch
> 
> None of the suggested workarounds in #2574 and #2632 resolves this issue. So this current extension release can not be installed successfully in a fresh TYPO3 10 installation. This is very frustrating and needs more attention for a stable version.

There are no collisions for standard TYPO3 10.4.4 setup:

```
composer create-project typo3/cms-base-distribution 2636-composer_dependency_collision
cd 2636-composer_dependency_collision
composer req apache-solr-for-typo3/solr:11.0.1
```

produces following output:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing solarium/solarium (4.2.0): Loading from cache
  - Installing typo3/cms-scheduler (v10.4.4): Downloading (100%)         
  - Installing typo3/cms-reports (v10.4.4): Downloading (100%)         
  - Installing apache-solr-for-typo3/solr (11.0.1): Downloading (100%)         
solarium/solarium suggests installing minimalcode/search (Query builder compatible with Solarium, allows simplified solr-query handling)
Writing lock file
Generating autoload files
Generating class alias map file
> typo3cms install:fixfolderstructure
No action performed!
> typo3cms install:generatepackagestates
The following extensions have been added to the generated PackageStates.php file: core, scheduler, extbase, fluid, frontend, fluid_styled_content, filelist, impexp, form, install, recordlist, backend, reports, setup, rte_ckeditor, about, belog, beuser, dashboard, extensionmanager, felogin, info, seo, sys_note, t3editor, tstemplate, viewpage, solr
```

See https://gist.github.com/dkd-kaehm/ec0f5024c51767c07d3b7b221a811258 for this scenario.

---

Even with the newer version of helhum/console, the installation works without any problems:

```
composer create-project typo3/cms-base-distribution 2636-composer_dependency_collision_typo3_console
cd 2636-composer_dependency_collision_typo3_console/
composer update helhum/typo3-console:6.3.1
composer req apache-solr-for-typo3/solr:11.0.1
```

---

@pschirch We can not reproduce any collision on current fresh install of TYPO3 10.4.4.
Please use Slacks ext-solr channel for this trouble. Create gist of your composer.json and composer.lock and describe the steps and messages in detail to reproduce this behaviour.

---

I'll close this issue in favour of #2636, which will be fixed in EXT:Solr v. 12+.

**Closed by dkd-kaehm** 2020-06-15 09:23 UTC

**Comment by wegewerk-mkb** [comment] 2020-10-15 09:41
> There are no collisions for standard TYPO3 10.4.4 setup

True, there are no composer errors. But installing `apache-solr-for-typo3/solr` will downgrade the event dispatcher:
```
- Downgrading symfony/event-dispatcher-contracts (v2.2.0 => v1.1.9): Loading from cache
- Downgrading typo3/symfony-psr-event-dispatcher-adapter (v2.0.0 => v1.0.0): Downloading (100%)
- Downgrading symfony/event-dispatcher (v5.1.7 => v4.4.15): Downloading (100%)
```
Which will lead to errors in the backend when saving records:
```
Fatal error: Declaration of TYPO3\SymfonyPsrEventDispatcherAdapter\EventDispatcherAdapter::dispatch(object $event, ?string $eventName = NULL): object must be compatible with Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch($event) in /var/www/html/backend/vendor/typo3/symfony-psr-event-dispatcher-adapter/src/EventDispatcherAdapter.php on line 35
```
Installing a newer version of solarium via composer alias (`"solarium/solarium": "5.2.0 as 4.2.0"`) is no solution since TYPO3 is then unable to contact the solr server. 

It seems impossible to install the solr extension on TYPO3 10.4.9
