### ISSUE TITLE
Re-Index after deleting a content element

### ISSUE THREAD

**Issue by heiko-hardt** [TYPO3-Solr/ext-solr#231] opened 2016-02-08 10:12 UTC
Hi, I thinks there may be a small bug in reindexing after deleting a content element.

By deleting a content element the page will directly removed from solr index.
This seems to be fine :), but there will be no update in the index-queue, so the page will not be re-indexed.

By hiding a content-element everything works like expected:
- direct remove from index
- updating the index-queue
- re-index page via scheduler

I'm using TYPO3 v.7.6.2 with flux, fluidpages and fluidcontent.
Not sure if this happens outside a "flux-environemt". It would be great if somebody else check this.

Kind regards
Heiko

**Comment by timoschmidt** [comment] 2016-02-08 16:34
Thanks for you report. We'll check this as soon as possible. Ot would be nice when you could debug this and provide a patch if needed.

**Comment by heiko-hardt** [comment] 2016-02-08 18:54
Hi timo, thanks for your reply.
I'm interesting in a fix, and will help as soon as possible. I will do my best having a closer look this week.
Regards Heiko

**Comment by markuskobligk** [comment] 2016-02-10 15:38
I can confirm this behaviour with TYPO3 7.6.2 and Solr 3.1.1 on a fresh installation without any Flux or other extensions.

**Comment by timoschmidt** [comment] 2016-04-04 09:26
@heiko-hardt 
@markuskobligk 

Did you had the chance yet to fix it or debug it?

**Comment by markuskobligk** [comment] 2016-04-04 09:38
I did not debug this yet, but Ingo added this to milestone 3.1.2, so I guess this will be fixed in the next TER version 3.1.2

**Comment by markuskobligk** [comment] 2016-04-04 10:54
I took a look at the RecordMonitor, the good news is that it is implemented already, but there is a logical error I think.

In the processCmdmap_preProcess() hook function which is called when a record is deleted the function updateItem() is called. In that function the last time the page item was changed is calculated by calling the function getItemChangedTime(). This is wrong in my opinion, the itemChangedTime should be the current timestamp, since I am changing the page RIGHT NOW when I delete some tt_content records from the page. The function updateItem() in Queue.php has to be changed to take a param if the iterm was changed due to a deletion I think, then it would be possible to distinguish between and real update and a change of the page by deleting something.

@timoschmidt : If you agree with this I'll provide a pull request for Classes/IndexQueue/Queue.php

**Comment by markuskobligk** [comment] 2016-04-04 11:46
I just saw that removing and adding the item again is not a solution because the addItem() function is private in Queue.php and can't be called from the RecordMonitor.php.

**Comment by timoschmidt** [comment] 2016-04-04 16:24
I am reopening the issue because we should fix this in the 3.1.x branch as well

**Comment by markuskobligk** [comment] 2016-04-04 17:14
I will create a merge request for the 3.1.x branch tommorrow.

**Comment by timoschmidt** [comment] 2016-04-04 17:15
Cool, thx :+1:

**Comment by timoschmidt** [comment] 2016-04-06 11:08
@markuskobligk 
Hi did you had the chance to apply the fix on 3.1.x?

**Comment by timoschmidt** [comment] 2016-04-06 14:36
Merged to dev-master and release-3.1.x

**Closed by timoschmidt** 2016-04-06 14:36 UTC
Labels: bug, help wanted

**Comment by markuskobligk** [comment] 2016-04-07 07:54
Hi Timo, sorry for not answering, but I was at home two days being ill.
